Models/IssueSetting.cs
using System;
using System.Collections.Generic;

namespace IMS.Models
{
    public partial class IssueSetting
    {
        public IssueSetting()
        {
            IssueProcesses = new HashSet<Issue>();
            IssueStatuses = new HashSet<Issue>();
            IssueTypes = new HashSet<Issue>();
        }

        public int Id { get; set; }
        public string Type { get; set; } = null!;
        public string Value { get; set; } = null!;
        public string Name { get; set; } = null!;
        public string? Description { get; set; }
        public string Color { get; set; } = null!;
        public bool? Status { get; set; }
        public int? ClassId { get; set; }
        public int? ProjectId { get; set; }

        public virtual Class? Class { get; set; }
        public virtual Project? Project { get; set; }
        public virtual ICollection<Issue> IssueProcesses { get; set; }
        public virtual ICollection<Issue> IssueStatuses { get; set; }
        public virtual ICollection<Issue> IssueTypes { get; set; }
    }
}

Models/Milestone.cs
using System;
using System.Collections.Generic;

namespace IMS.Models
{
    public partial class Milestone
    {
        public Milestone()
        {
            Issues = new HashSet<Issue>();
        }

        public int Id { get; set; }
        public string Title { get; set; } = null!;
        public string? Description { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? ProjectId { get; set; }
        public int ClassId { get; set; }
        public int? AssignmentId { get; set; }
        public bool? Status { get; set; }

        public virtual Assignment? Assignment { get; set; }
        public virtual Class Class { get; set; } = null!;
        public virtual Project? Project { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
    }
}

ViewModels/Class/ClassViewModel.cs

namespace IMS.ViewModels.Class
{
    public  class ClassViewModel
    {
        public ClassViewModel()
        {
            IssueSettings = new HashSet<IssueSetting>();
            Milestones = new HashSet<IMS.Models.Milestone>();
            Projects = new HashSet<Project>();
            Students = new HashSet<Models.User>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        
        public string Name { get; set; } = null!;
        public string? Description { get; set; }
        public int? TeacherId { get; set; }
        public int? SubjectId { get; set; }
        public bool IsActive { get; set; }

        public virtual Models.Subject? Subject { get; set; }
        public virtual Models.User? Teacher { get; set; }
        public virtual ICollection<IssueSetting> IssueSettings { get; set; }
        public virtual ICollection<IMS.Models.Milestone> Milestones { get; set; }
        public virtual ICollection<Project> Projects { get; set; }

        public virtual ICollection<Models.User> Students { get; set; }
    }
}

ViewModels/Milestone/MilestoneViewModel.cs
namespace IMS.ViewModels.Milestone
{
    public class MilestoneViewModel
    {
           public MilestoneViewModel()
            {
                Issues = new HashSet<Issue>();
            }

            public int Id { get; set; }
            public string Title { get; set; } = null!;
            public string? Description { get; set; }
            public DateTime? StartDate { get; set; }
            public DateTime? EndDate { get; set; }
            public int? ProjectId { get; set; }
            public int ClassId { get; set; }
            public int? AssignmentId { get; set; }

            public virtual Assignment? Assignment { get; set; }
            public virtual IMS.Models.Class Class { get; set; } = null!;
            public virtual Project? Project { get; set; }
            public virtual ICollection<Issue> Issues { get; set; }
        }
    }

ViewModels/Validation/IssueSettingViewModel.cs
namespace IMS.ViewModels.Validation
{
    public class IssueSettingViewModel
    {
        public int? Id { get; set; }
        [Required(ErrorMessage = "Type is required")]
        public string Type { get; set; } = null!;
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; } = null!;
        [Required(ErrorMessage = "Value is required")]
        public string Value { get; set; } = null!;
        [Required(ErrorMessage = "Color is required")]
        public string Color { get; set; } = null!;
        public string? Description { get; set; }
        public bool Status { get; set; }
        public int? ProjectId { get; set; }
        public int? ClassId { get; set; }
    }
}

Controllers/ClassController.cs
using DocumentFormat.OpenXml.Drawing.Diagrams;
using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Wordprocessing;
using IMS.Models;
using IMS.Services;
using IMS.ViewModels.Class;
using IMS.ViewModels.Milestone;
using IMS.ViewModels.Validation;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;

namespace IMS.Controllers
{
    [Route("/Class")]
    public class ClassController : Controller
    {
        private readonly IClassService _classService;
        private readonly IUserService _userService;
        private readonly IMilestoneService _milestoneService;
        private readonly IssueSettingDAO _isDAO;
        public ClassController(IClassService classService, IUserService userService, IMilestoneService milestoneService, IssueSettingDAO isDAO)
        {
            _classService = classService;
            _userService = userService;
            _milestoneService = milestoneService;
            _isDAO = isDAO;
        }
        [HttpGet, Route("Index")]
        [CustomAuthorize]
        public IActionResult Index(int? pageNumber, bool? filterbyStatus, string? searchByValue, string? filterByTeacher, string? filterBySubject, [FromServices] IChkPgAcessService chkPgAcess)
        {
            int tempPageNumber = pageNumber ?? 1;
            int tempPageSize = 10;
            Paginate<Class> paginate = new Paginate<Class>(tempPageNumber, tempPageSize);
            User user = HttpContext.Session.GetUser();

            Dictionary<string, dynamic> filter = new Dictionary<string, dynamic>(), search = new Dictionary<string, dynamic>();
            IEnumerable<Class> classes = new List<Class>();
            if (user.Role.Value == RoleUser.Admin || user.Role.Value == RoleUser.Manager)
            {
                classes = _classService.GetClasses();
                ViewBag.ClassList = _classService.GetClasses();
            }
            if (user.Role.Value == RoleUser.Student)
            {
                classes = _classService.GetClassesByStudent(user.Id);
                ViewBag.ClassList = _classService.GetClassesByTeacher(user.Id);
            }
            if (user.Role.Value == RoleUser.Teacher)
            {
                classes = _classService.GetClassesByTeacher(user.Id);
                ViewBag.ClassList = _classService.GetClassesByTeacher(user.Id);
            }
            if (filterByTeacher != null && !filterByTeacher.Equals("All"))
            {
                int teacherid = _classService.GetTeacherIdByNameAndEmail(filterByTeacher);
                classes = classes.Where( c=> c.TeacherId == teacherid).ToList();
            }
            if (filterbyStatus != null && !filterbyStatus.Equals("All"))
            {
                classes = classes.Where(c => c.IsActive == filterbyStatus).ToList();
            }
            if (filterBySubject != null && !filterBySubject.Equals("All"))
            {
                int subjectid = _classService.GetSubjectId(filterBySubject);
                classes = classes.Where(c => c.SubjectId == subjectid).ToList();
            }

            if (!string.IsNullOrEmpty(searchByValue))
            {
                classes = classes.Where( c=> c.Name.ToLower().Contains(searchByValue.ToLower())).ToList();


            }

            ViewBag.TeacherValue = _classService.GetAllTeachers();
            ViewBag.StatusValue = filterbyStatus;
            ViewBag.SubjectValue = _classService.GetSubjects();
            ViewBag.SearchValue = searchByValue;
           
            var subject = _classService.GetSubjects();
                ViewBag.Subject = subject;
                ViewBag.Action = "ClassList";
            ViewBag.ClassList = paginate.GetListPaginate(classes.ToList());
            ViewBag.Pagination = paginate.GetPagination();
            ViewBag.PageAccess = chkPgAcess.GetPageAccess(HttpContext);
            return View();
            
        }

        [HttpGet("Details/{id}")]
        [CustomAuthorize]
        public IActionResult Details(int id, [FromServices] IChkPgAcessService chkPgAcess)
        {
            var subject = _classService.GetSubjects();
            ViewBag.Subject = subject;
            var teacher = _userService.GetTeacher();
            ViewBag.Teacher = teacher;
            var Class = _classService.GetClass(id);
            ViewBag.ErrorMessage = TempData["ErrorMessage"] as string;
            if (Class == null)
            {
                return NotFound();
            }
            ClassViewModel ClassViewModel = new ClassViewModel()
            {
                Id = Class.Id,
                Name = Class.Name,
                Description = Class.Description,
                TeacherId = Class.TeacherId,
                SubjectId = Class.SubjectId,
                IsActive = Class.IsActive,
                Teacher = Class.Teacher,
                Subject = Class.Subject,
                Milestones = Class.Milestones,
                IssueSettings = Class.IssueSettings
            };
            ViewBag.PageAccess = chkPgAcess.GetPageAccess(HttpContext);
            return View(ClassViewModel);
        }

        [HttpGet("Create")]
        [CustomAuthorize]
        public IActionResult Create()
        {
            var subject = _classService.GetSubjects();
            ViewBag.Subject = subject;
            return View();

        }

        [HttpPost("Create")]
        public IActionResult Create(ClassViewModel classViewModel, string teacherInput)
        {
            if (!ModelState.IsValid)
            {
                var subject2 = _classService.GetSubjects();
                ViewBag.Subject = subject2;
                return View();
            }
            bool ClassExist = _classService.ClassExist(classViewModel.Name);
            if(ClassExist) 
            {
                var subject4 = _classService.GetSubjects();
                ViewBag.Subject = subject4;
                ViewBag.ErrorMessage = " Class is already exist.";
                return View();
            }
            var teacherid = _classService.GetTeacherIdByNameAndEmail(teacherInput);
            if (teacherid == 0)
            {
                var subject3 = _classService.GetSubjects();
                ViewBag.Subject = subject3;
                ViewBag.ErrorMessage = " Teacher is not exist.";
                return View();
            }

            classViewModel.IsActive = true;
            Class Class = new Class()
            {
                Name = classViewModel.Name,
                Description = classViewModel.Description,
                TeacherId = teacherid,
                SubjectId = classViewModel.SubjectId,
                IsActive = classViewModel.IsActive
            };
            _classService.AddClass(Class);
            var assignments = _classService.GetAssignments(Class.SubjectId??0);
            foreach (var assignment in assignments)
            {
                var milestone = new Milestone
                {
                    Title = $"Initial Milestone for Class {Class.Name}",
                    Description = "Description for the initial milestone",
                    StartDate = DateTime.Now,
                    EndDate = DateTime.Now.AddDays(30),
                    ClassId = Class.Id,
                    AssignmentId = assignment.Id,
                    Status = true
                };
                _milestoneService.AddMilestone(milestone);
            }
        

            var subject = _classService.GetSubjects();
            ViewBag.Subject = subject;
            ViewBag.SuccessMessage = "Add class success!";
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Update(ClassViewModel classViewModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            var subject = _classService.GetSubjects();
            ViewBag.Subject = subject;
            var teacher = _userService.GetTeacher();
            ViewBag.Teacher = teacher;
            Class Class1 = _classService.GetClass(classViewModel.Id);
            Class1.SubjectId = classViewModel.SubjectId;  
           Class1.TeacherId = classViewModel.TeacherId;
            bool ClassExist = _classService.ClassExist(classViewModel.Name);
            if(ClassExist && Class1.Name!=classViewModel.Name)
            {
                var subject2 = _classService.GetSubjects();
                ViewBag.Subject = subject2;
                var teacher2 = _userService.GetTeacher();
                ViewBag.Teacher = teacher2;

                TempData["ErrorMessage"] = "Class is already exist.";
                return RedirectToAction("Details",new { id= classViewModel.Id });
                
            }
            Class1.Name = classViewModel.Name;
            Class1.IsActive = classViewModel.IsActive;
            Class1.Description = classViewModel.Description;
            _classService.UpdateCLass(Class1);
            return RedirectToAction("Index");
        }
        [HttpPost("UpdateStatus")]
        public IActionResult ToggleStatus(int id)
        {
            var Class = _classService.GetClass(id);

            if (Class == null)
            {
                return NotFound();
            }

            Class.IsActive = !Class.IsActive;

            _classService.UpdateCLass(Class);

            return RedirectToAction("Index");
        }
        [HttpGet("People/{id}")]
        [CustomAuthorize]
        public IActionResult People(int id, string searchString, string filterbyStatus, [FromServices] IChkPgAcessService chkPgAcess)
        {



Views/Class/Create.cshtml
@{
}
<h2 class="mb-4">Create Class</h2>
@model IMS.ViewModels.Class.ClassViewModel
<form asp-action="Create" method="post" enctype="multipart/form-data">
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }
    @if (ViewBag.SuccessMessage != null)
    {
        <div class="alert alert-success">
            <ul>
                <li>@ViewBag.SuccessMessage</li>
            </ul>
        </div>
    }
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            <ul>
                <li>@ViewBag.ErrorMessage</li>
            </ul>
        </div>
    }
    <input type="hidden" name="_token" value="@ViewBag.Token" />

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Name*</label>
                <div class="col-10">
                    <input id="Name" name="Name" asp-for="Name" class="form-control" required />
                    <span id="nameError" asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label>Description (Optional)</label>
                <div class="col-10">
                    <input asp-for="Description" class="form-control" />
                </div>
            </div>
        </div>

        <div class="col-md-6">


            <div class="form-group">
                <label for="teacherInput">Teacher (Email/Name)*</label>
                <div class="col-10">
                    <input type="text" class="form-control" id="teacherInput" name="teacherInput" required />
                </div>
            </div>

            <div class="form-group">
                <label for="roleId">Subject*</label>
                <div class="col-10">
                    <select class="form-control" id="SubjectId" name="SubjectId">
                        @foreach (var subject in ViewBag.Subject)
                        {
                            <option value="@subject.Id">@subject.Name</option>
                        }
                    </select>
                </div>
            </div>
        </div>

     @*   <div id="milestonesContainer">
            <!-- Duyệt qua danh sách các Milestone đã thêm để hiển thị -->
            @foreach (var Milestone in Model.Milestones)
            {
                <div class="milestone">
                    <div class="form-group">
                        <label for="milestones.Title">Milestone Title</label>
                        <input type="text" class="form-control" name="milestones.Title" value="@Milestone.Title" readonly />
                    </div>

                    <div class="form-group">
                        <label for="milestones.Description">Milestone Description</label>
                        <textarea class="form-control" name="milestones.Description" readonly>@Milestone.Description</textarea>
                    </div>
                </div>
            }
        </div>*@
    </div>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <button type="submit" class="btn btn-primary">Create</button>
            <button type="reset" class="btn btn-primary">Reset</button>
            <a href="/Class" class="btn btn-primary">Back to Classes</a>
        </div>
    </div>
 
  
</form>

Views/Class/Details.cshtml
@model IMS.ViewModels.Class.ClassViewModel;
@{
    IMS.ViewModels.Permission.PageAccess pageAcess = ViewBag.PageAccess;
}

<html lang="en">

<body>
    
        <div class="container-fluid px-4">
        <div class="d-flex">
            <a asp-action="Details" asp-controller="Class" asp-route-id="@Model.Id" class="btn  btn-outline-primary text-decoration-none">General</a>
            <a asp-action="People" asp-controller="Class" asp-route-id="@Model.Id" class="btn btn-outline-primary text-decoration-none">People</a>
            <a asp-action="Milestones" asp-controller="Class" asp-route-id="@Model.Id" class="btn  btn-outline-primary text-decoration-none">Milestone</a>
            <a asp-action="IssueSetting" asp-controller="Class" asp-route-id="@Model.Id" class="btn  btn-outline-primary text-decoration-none">Issue Setting</a>
        </div>

            <div class="card mb-4">
                <div class="card-body">
              
                    
                    <form method="post" asp-action="Update" enctype="multipart/form-data">

                    @if (!ViewData.ModelState.IsValid)
                    {
                        <div class="alert alert-danger">
                            <ul>
                                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                                {
                                    <li>@error.ErrorMessage</li>
                                }
                            </ul>
                        </div>
                    }
                    @if (ViewBag.SuccessMessage != null)
                    {
                        <div class="alert alert-success">
                            <ul>
                                <li>@ViewBag.SuccessMessage</li>
                            </ul>
                        </div>
                    }
                    @if (ViewBag.ErrorMessage != null)
                    {
                        <div class="alert alert-danger">
                            <ul>
                                <li>@ViewBag.ErrorMessage</li>
                            </ul>
                        </div>
                    }
                    <div class="row">
                        <input type="hidden" asp-for="Id" value="@Model.Id" />
                                       
                        <div id="generalSection">
                       
                            @if (pageAcess.CanUpdate)
                            {
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Class Name*</label>
                                        <input type="text" name="Name" asp-for="Name" class="form-control" value="@Model.Name" required />
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Class Name*</label>
                                        <input type="text" name="Name" asp-for="Name" class="form-control" value="@Model.Name" required readonly/>
                                    </div>
                                </div>
                            }
                            @if (pageAcess.CanUpdate)
                           {
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="TeacherId">Teacher</label>
                                        <select name="TeacherId" class="form-control" >
                                            @foreach (var teacher in ViewBag.Teacher)
                                            {
                                                <option value="@teacher.Id" name="TeacherId" selected="@(teacher.Id == Model.TeacherId)">@teacher.Name</option>
                                            }
                                        </select>
                                        <input type="hidden" name="TeacherId" value="@Model.TeacherId" />
                                    </div>
                                </div>
                           }
                           else
                           {
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="TeacherId">Teacher</label>
                                        <select name="TeacherId" class="form-control" disabled>
                                            @foreach (var teacher in ViewBag.Teacher)
                                            {
                                                <option value="@teacher.Id" name="TeacherId" readonly selected="@(teacher.Id == Model.TeacherId)">@teacher.Name</option>
                                            }
                                        </select>
                                        <input type="hidden" name="TeacherId" value="@Model.TeacherId" />
                                    </div>
                                </div>
                           }
                            @if (pageAcess.CanUpdate)
                            {
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="SubjectId">Subject</label>
                                        <select name="SubjectId" class="form-control">
                                            @foreach (var subject in ViewBag.Subject)
                                            {
                                                <option value="@subject.Id" name="SubjectId"  selected="@(subject.Id == Model.SubjectId)">@subject.Name</option>
                                            }
                                        </select>
                                        <input type="hidden" name="SubjectId" value="@Model.SubjectId" />
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="SubjectId">Subject</label>
                                        <select name="SubjectId" class="form-control" disabled>
                                            @foreach (var subject in ViewBag.Subject)
                                            {
                                                <option value="@subject.Id" name="SubjectId" readonly selected="@(subject.Id == Model.SubjectId)">@subject.Name</option>
                                            }
                                        </select>
                                        <input type="hidden" name="SubjectId" value="@Model.SubjectId" />
                                    </div>
                                </div>
                            }
                            @if (pageAcess.CanUpdate)
                            {
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea name="description" class="form-control">@Model.Description</textarea>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea name="description" readonly class="form-control">@Model.Description</textarea>
                                    </div>
                                </div>
                            }
                            @if (pageAcess.CanUpdate)
                            {
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="statusToggle">Status</label>
                                        <div class="form-check form-switch">
                                            <input type="hidden" name="IsActive" value="false" />
                                            <input type="checkbox" class="form-check-input" id="statusToggle" name="Status" @(Model.IsActive ? "checked" : "") onchange="changeStatus()" />
                                        </div>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="statusToggle">Status</label>
                                        <div class="form-check form-switch">
                                            <input type="hidden" name="IsActive" value="false" />
                                            <input type="checkbox" class="form-check-input"  disabled id="statusToggle" name="Status" @(Model.IsActive ? "checked" : "") onchange="changeStatus()" />
                                        </div>
                                    </div>
                                </div>
                            }
                           
                        </div>
                    </div>

                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary">Save</button>
                            <a href="/Class/Index" class="btn btn-primary">Back to Class List</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

       
    

<script>
    function changeStatus() {
        var statusToggle = document.getElementById('statusToggle');
        var statusLabel = document.querySelector('.form-check-label');


        statusToggle.previousElementSibling.value = statusToggle.checked ? "true" : "false";



    }
</script>
    <script>
        function validateForm() {
            var nameInput = document.getElementById('Name');
            var emailInput = document.getElementById('Email');
            var nameError = document.getElementById('nameError');
            var emailError = document.getElementById('emailError');

            // Reset previous errors
            nameError.innerHTML = "";
            emailError.innerHTML = "";

            // Validate Name (non-empty)
            if (nameInput.value.trim() === "") {
                nameError.innerHTML = "Name is required.";
                return false; // Prevent form submission
            }

            // Validate Email (non-empty and valid format)
            var emailRegex = ;
            if (emailInput.value.trim() === "") {
                emailError.innerHTML = "Email is required.";
                return false; // Prevent form submission
            } else if (!emailRegex.test(emailInput.value)) {
                emailError.innerHTML = "Invalid email format.";
                return false; // Prevent form submission
            }

            // Form is valid
            return true;
        }
    </script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/js/scripts.js"></script>
</body>
</html>