Controllers/UserProfileController.cs
using Firebase.Auth;
using Firebase.Storage;
using Microsoft.AspNetCore.Mvc;
using IMS.ViewModels.Auth;

namespace IMS.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly IMSContext _context;
        private static string ApiKey = "AIzaSyBjstBnMJX7h_NlJ5-vqcQE0V-Ldaztnk8";
        private static string Bucket = "imsmanagement-35781.appspot.com";
        private static string AuthEmail = "abc@gmail.com";
        private static string AuthPassword = "123456";
        public UserProfileController(IMSContext context)
        {
            _context = context;
        }
        [Route("/userprofile")]
        [CustomAuthorize]
        public IActionResult User([FromQuery] string tab)
        {
            try
            {
                ViewData["tab"] = tab ?? "userdetails";
                switch (tab)
                {
                    case "userdetails":
                        {
                            int? id = HttpContext.Session.GetUser()?.Id;
                            var User = _context.Users.SingleOrDefault(u => u.Id == id);
                            return View("UserDetail", User);
                        }

                   

                }
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error:" + ex.Message;
                return View();
            }

        }
        public async Task<IActionResult> EditUserProfile()
        {
            try
            {
                int? id = HttpContext.Session.GetUser()?.Id;
                var User = _context.Users.SingleOrDefault(u => u.Id == id);
                return View(User);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error:" + ex.Message;
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUserProfile([Bind("Id,Name,Phone,Address,Gender")] Models.User User)
        {
            try
            {
                Models.User user = _context.Users.Find(User.Id);
                user.Name = User.Name;
                user.Phone = User.Phone;
                user.Address = User.Address;
                user.Gender = User.Gender;
                _context.SaveChanges();

                return RedirectToAction(nameof(Index), new { tab = "userdetails" });
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error:" + ex.Message;
                return RedirectToAction(nameof(Index), new { tab = "userdetails" });
            }


        }


        [HttpPost]
        public async Task<IActionResult> CreateAvatar(IFormFile file)
        {
            try
            {
                // Xử lý tạo avatar và lưu vào cơ sở dữ liệu
                if (file != null && file.Length > 0)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Avatars", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }


                    var fileStream2 = new FileStream(filePath, FileMode.Open);
                    var downloadLink = await Upload(fileStream2, file.FileName);
                    int? id = HttpContext.Session.GetUser()?.Id;
                    Models.User avatar = _context.Users.SingleOrDefault(u => u.Id == id);
                    avatar.Avatar = downloadLink;
                    _context.SaveChanges();
                    ViewBag.Success = "Create avatar successful.";
                }

                return RedirectToAction(nameof(Index), new { tab = "userdetails" });
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error:" + ex.Message;
                return RedirectToAction(nameof(Index), new { tab = "userdetails" });
            }

        }
        public async Task<string> Upload(FileStream stream, string filename)
        {
            var auth = new FirebaseAuthProvider(new FirebaseConfig(ApiKey));
            var a = await auth.SignInWithEmailAndPasswordAsync(AuthEmail, AuthPassword);
            var cancellation = new CancellationTokenSource();
            var task = new FirebaseStorage(
                Bucket,
                new FirebaseStorageOptions
                {
                    AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken),
                    ThrowOnCancel = true
                }
                ).Child("User")
                 .Child(filename)
                 .PutAsync(stream, cancellation.Token);
            try
            {
                string link = await task;
                return link;

            }
            catch (Exception ex)
            {

                Console.WriteLine("Exception was thrown : {0}", ex);
                return null;
            }
        }


        [HttpPost]
        public async Task<IActionResult> UpdateAvatar(IFormFile file)
        {
            try
            {
                int? id = HttpContext.Session.GetUser()?.Id;
                // Xử lý cập nhật avatar và lưu vào cơ sở dữ liệu
                var existingAvatar = _context.Users.FirstOrDefault(u => u.Id == id);

                if (existingAvatar.Avatar != null)
                {
                    string[] arr = existingAvatar.Avatar.Split('=');
                    if (file != null && file.Length > 0)
                    {
                        //// Xóa file avatar 
                        //var oldFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Avatars");
                        //// Tạo đối tượng DirectoryInfo
                        //DirectoryInfo directoryInfo = new DirectoryInfo(oldFilePath);

                        //// Lấy danh sách tất cả các tệp tin trong thư mục
                        //FileInfo[] files = directoryInfo.GetFiles();

                        //// Xóa tất cả các tệp tin
                        //foreach (FileInfo fileOfAvatars in files)
                        //{

                        //    fileOfAvatars.Delete();
                        //}

                        // Tạo file avatar mới
                        var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Avatars", fileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }

                        // Cập nhật thông tin avatar trong cơ sở dữ liệu
                        var fileStream2 = new FileStream(filePath, FileMode.Open);
                        var downloadLink = await Upload(fileStream2, file.FileName);
                        existingAvatar.Avatar = downloadLink;
                        _context.SaveChanges();


                        ViewBag.Success = "Update avatar successful.";

                    }
                }

                return RedirectToAction(nameof(Index), new { tab = "userdetails" });
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error:" + ex.Message;
                return RedirectToAction(nameof(Index), new { tab = "userdetails" });
            }

        }


        [HttpPost]
        public IActionResult DeleteAvatar()
        {
            try
            {
                int? id = HttpContext.Session.GetUser()?.Id;
                // Xử lý xóa avatar và cập nhật cơ sở dữ liệu
                var avatarToDelete = _context.Users.FirstOrDefault(a => a.Id == id);

                if (avatarToDelete.Avatar != null)
                {
                    // Xóa file avatar
                    //var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Avatars", avatarToDelete.Avatar);
                    //System.IO.File.Delete(filePath);

                    // Xóa avatar trong cơ sở dữ liệu
                    // Cập nhật thông tin avatar trong cơ sở dữ liệu
                    avatarToDelete.Avatar = null;
                    _context.SaveChanges();
                }
                ViewBag.Success = "Delete avatar successful";
                return RedirectToAction(nameof(Index), new { tab = "userdetails" });
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error:" + ex.Message;
                return RedirectToAction(nameof(Index), new { tab = "userdetails" });
            }

        }


        
    }
}

Views/UserProfile/Index.cshtml
@model IMS.Models.User;

@{
    ViewData["Title"] = "Index";
    string tab = ViewData["tab"]?.ToString() ?? "userdetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    ViewBag.Title = "Avatar Management";
}
<style>
    .popup {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        border: 1px solid #ccc;
        padding: 20px;
        background-color: #fff;
        z-index: 1;
        width:450px;
    }

    .popup-content {
        /*text-align: center;*/
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
        cursor: pointer;
    }

        .close:hover {
            color: black;
        }
        .avatar {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            border: 3px solid #000;
            overflow: hidden;
        }

        .avatar img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        .avatarAdd{
        width: 50px;
        height: 50px;
        overflow: hidden;
        margin-left: 35px;
        margin-top: 10px;
        }

        .avatarAdd img {
            width: 60%;
            object-fit: cover;
            border-radius:50%;

        }
        .avatarAdd :hover{
            background-color:gray;
        }
        .active-color{
                background-color: green !important;
                color: #f8f9fa;
        }
</style>
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a id="Home"  class="nav-link @(@tab == "userdetails" ? "active-color":"")" href="/userprofile?tab=userdetails">User Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/userprofile?tab=changepassword">Change Password</a>
    </li>
   
</ul>
<h1>User Details</h1>

@if ( Model.Avatar == null){
    <div class="avatar">
        <img src="~/img/avatarDemo.jpg" alt="Avatar">
    </div>
    <div class="avatarAdd" >
        <img src="~/img/addAvatar.png" alt="Thumbnail" class="thumbnail" onclick="openPopup('popupAdd')">
    </div>
   
}
else 
{
    <div class="avatar" style=" border: 1px solid #000;">
        <img src="@Html.DisplayFor(model => model.Avatar)" alt="Avatar" class="avatar" />

    </div>
    <div class="avatarAdd">
        <img src="~/img/editAvatar.png" alt="Thumbnail" class="thumbnail" onclick="openPopup('popupEdit')">
    </div>

    
}

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @if(Model.Gender==true){
                <p>Male</p>
            }
            else if (Model.Gender == null)
            {
                <p></p>
            }
            else{
                <p>Female</p>
            }
        </dd>
    </dl>
</div>
<div style="display:flex">
    <div style="background-image: linear-gradient(195deg, #66BB6A 0%, #43A047 100%); height:fit-content; border-radius:5px; display:flex;justify-content:center;width:fit-content;padding:5px">
        <button style="color:white; text-decoration:none;background-image: linear-gradient(195deg, #66BB6A 0%, #43A047 100%); border:none"
                onclick="openPopup('popupEditDetails')">
            Edit profile
        </button>
    </div>
   
</div>

<div class="modal" tabindex="-1" id="popupEditDetails" style="background-color:#2220208c">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Edit profile</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="closePopup('popupEditDetails')"></button>
            </div>
            <!-- Nội dung của popup edit detail-->
            <div class="row" style="padding:10px">
                <form asp-action="EditUserProfile" id="form">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" disabled />
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" id="Name" class="form-control" />
                        <span id="nameError" style="color:rgba(var(--bs-danger-rgb));" class="field-validation-error"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" id="Phone" class="form-control" />
                        <span id="phoneError" style="color:rgba(var(--bs-danger-rgb));" class="field-validation-error"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        @if (Model.Gender == true)
                        {
                            <label><input asp-for="Gender" type="radio" value="true" checked /> Male</label>
                            <label><input asp-for="Gender" type="radio" value="false" /> Female</label>

                        }
                        else if (Model.Gender == null)
                        {
                            <label><input asp-for="Gender" type="radio" value="true" /> Male</label>
                            <label><input asp-for="Gender" type="radio" value="false" /> Female</label>
                        }
                        else
                        {
                            <label><input asp-for="Gender" type="radio" value="true" /> Male</label>
                            <label><input asp-for="Gender" type="radio" value="false" checked /> Female</label>


                        }
                    </div>
                    <div class="form-group" style="float:right">
                        <input style="background-color: #43A047;border-color: #43A047; height:40px;"
                               type="button" value="Save" class="btn btn-primary" 
                               onclick="validateAndSubmit()" />
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="closePopup('popupEditDetails')" style="height:40px">Close</button>

                    </div>
                </form>
            </div>

            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="closePopup('popupEditDetails')">Close</button>*@
            </div>
        </div>
    </div>
</div>


    <!-- Popup Add -->
<div class="modal" tabindex="-1" id="popupAdd" style="background-color:#2220208c">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Create avatar</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="closePopup('popupAdd')"></button>
            </div>
            <div class="modal-body">
                <!-- Nội dung của popup add -->
                @using (Html.BeginForm("CreateAvatar", "UserProfile", FormMethod.Post, new { enctype = "multipart/form-data", style = "display: flex;" }))
                {
                    @Html.HiddenFor(model => model.Id)

                    <label for="file">Choose Avatar:</label>
                    <input type="file" name="file" id="file" required />
                    <input type="submit" value="Create" style="background-color: #43A047;border-radius: 3px;" />
                }
            </div>
        </div>
    </div>
</div>
   
<!-- Popup Edit -->
<div class="modal" tabindex="-1" id="popupEdit" style="background-color:#2220208c">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Edit avatar</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="closePopup('popupEdit')"></button>
            </div>
            <!-- Nội dung của popup edit -->
            <div class="modal-body">
                <p>
                    @using (Html.BeginForm("UpdateAvatar", "UserProfile", FormMethod.Post, new { enctype = "multipart/form-data", style = "display: flex;" }))
                {
                    @Html.HiddenFor(model => model.Id)

                    <label for="file">Update Avatar:</label>
                    <input type="file" name="file" id="file" required />
                        <input type="submit" value="Update" style="background-color: #43A047;border-radius: 3px;height: fit-content;" />
                }
                </p>
                <p>
                        <label for="file">Delete Avatar:</label>
                        <input type="submit" value="Delete" onclick="openPopup('popupDelete')" style="background-color: #43A047;border-radius: 3px; margin-top:5px" />
                </p>
            </div>
            
        </div>
    </div>
</div>


<!---popupdelete--->
<div class="modal" tabindex="-1" id="popupDelete" style="background-color:#2220208c">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Confirm delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="closePopup('popupDelete')"></button>
            </div>
            <!-- Nội dung của popup delete -->
            <div class="modal-body">
                Are you sure you want to delete this avatar?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("DeleteAvatar", "UserProfile", FormMethod.Post))
                {
                    @Html.HiddenFor(model => model.Id)
                    <input type="submit" value="Yes" onclick="closePopup('popupDelete')" style="background-color: #43A047;border-radius: 3px; margin-top:5px" />
                }
                <input type="submit" value="No" onclick="closePopup('popupDelete')" style="background-color: #43A047;border-radius: 3px; margin-top:9px" />

            </div>
        </div>
    </div>
</div>


<script>
    var popup = document.getElementById('popupDeleteSuccess');
    popup.style.display = 'block';
            
     function openPopup(popupView) {
        var popup = document.getElementById(popupView);
            popup.style.display = 'block';
        }

    function closePopup(popupView) {
        var popup = document.getElementById(popupView);
            popup.style.display = 'none';
        }

   function validateAndSubmit() {
        // Lấy giá trị từ thẻ input
        var phoneInput = $("#Phone");
        var nameInput = $("#Name");
        var phoneError = $("#phoneError");
        var nameError = $("#nameError");

        // Reset trạng thái và thông báo lỗi trước mỗi lần kiểm tra
        phoneInput.removeClass("input-validation-error");
        nameInput.removeClass("input-validation-error");
        phoneError.text("");
        nameError.text("");

        // Lấy giá trị từ thẻ input
        var phoneValue = phoneInput.val();
        var nameValue = nameInput.val();

        // Biểu thức chính quy để kiểm tra số điện thoạ i (chỉ cho phép chữ số)
        var phoneRegex = /^0[0-9]{9}$/;

        // Kiểm tra

        if (!phoneRegex.test(phoneValue)&& phoneValue!="") {
            // Hiển thị thông báo lỗi và đặt lỗi cho trường input
            //phoneInput.addClass("input-validation-error");
            phoneError.text("Invalid phone number, phone number has 10 digits and starts with 0.");
        } 
        else if (nameValue==""){
            nameError.text("Please enter a name.");
        }
        else {
            // Validation thành công, tiếp tục submit form
            document.forms["form"].submit();
            //$("form").submit/*();*/
        }
    }
</script>